const FETCH_ALL_PRODUCT_ACTION = {
    FETCH_PRODUCT_BEGIN: "FETCH_PRODUCT_BEGIN",
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",
};

const FILTER_ACTION = {
    SORT_BY_LOW_HIGH: "SORT_BY_LOW_HIGH",
    SORTY_BY_RATING: "SORT_BY_RATING",
    SORT_BY_CATEGORY: "SORT_BY_CATEGORY",
    SORT_BY_PRICE: "SORT_BY_PRICE",
    RESET_FILTER: "RESET_FILTER",
};

export { FETCH_ALL_PRODUCT_ACTION, FILTER_ACTION };