const FETCH_ALL_PRODUCT_ACTION = {
  FETCH_PRODUCT_BEGIN: "FETCH_PRODUCT_BEGIN",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",
};

const FILTER_ACTION = {
  SORT_BY_LOW_HIGH: "SORT_BY_LOW_HIGH",
  SORTY_BY_RATING: "SORT_BY_RATING",
  SORT_BY_CATEGORY: "SORT_BY_CATEGORY",
  SORT_BY_PRICE: "SORT_BY_PRICE",
  SORT_BY_SEARCH: "SORT_BY_SEARCH",
  RESET_FILTER: "RESET_FILTER",
};

const CART_ACTION = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  LOADING: "LOADING",
  CLEARCART: "CLEARCART",
  ERROR: "ERROR",
};

const WISHLIST_ACTION = {
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  LOADING: "LOADING",
  ERROR: "ERROR",
};

const USER_AUTH_ACTION = {
  INITAL_RELOAD: "INITIAL_RELOAD",
  LOGIN_SUCCESSFULL: "LOGIN_SUCCESSFULL",
  LOGOUT_SUCCESSFULL: "LOGOUT_SUCCESSFULL",
};
export {
  FETCH_ALL_PRODUCT_ACTION,
  FILTER_ACTION,
  CART_ACTION,
  USER_AUTH_ACTION,
};
export { WISHLIST_ACTION };
