const FETCH_ALL_PRODUCT_ACTION = {
    FETCH_PRODUCT_BEGIN: "FETCH_PRODUCT_BEGIN",
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",
};

const FILTER_ACTION = {
    SORT_BY_LOW_HIGH: "SORT_BY_LOW_HIGH",
    SORTY_BY_RATING: "SORT_BY_RATING",
    SORT_BY_CATEGORY: "SORT_BY_CATEGORY",
    SORT_BY_PRICE: "SORT_BY_PRICE",
    RESET_FILTER: "RESET_FILTER",
};

const CART_ACTION = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    DECREASE_QUANTITY: "DECREASE_QUANTITY",
    LOADING: "LOADING",
    ERROR: "ERROR",
};
export { FETCH_ALL_PRODUCT_ACTION, FILTER_ACTION, CART_ACTION };